os:
  - linux
  - windows

sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
  - "8"
  - "10"

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test-cover

after_script:
  - npm run coveralls

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
